# Generated by Django 5.0.3 on 2024-03-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApplication', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=10),
        ),
    ]
